# Generated by Django 6.0 on 2025-12-07 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='ativo', max_length=20)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alugueis', to='cars.carro')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alugueis_registrados', to=settings.AUTH_USER_MODEL)),
                ('perfil_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alugueis', to='users.perfilcliente')),
            ],
        ),
    ]
