# Generated by Django 5.2.9 on 2025-12-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rename_valor_aluguel_valor_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
