# Generated by Django 6.0 on 2025-12-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('ano', models.IntegerField()),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('alugado', 'Alugado')], default='disponivel', max_length=20)),
            ],
        ),
    ]
